services:
  mysql:
    image: mysql:8.0
    container_name: swapi-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: swapi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
  airflow:
    build: .
    container_name: swapi-airflow
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - AIRFLOW_HOME=/opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: bash -lc "airflow standalone"
volumes:
  mysql_data:
